on:
  push:
    branches:
      - main
      
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      
    - name: Build Project
      run: |
        npm install
        npm run build
    
    - name: SFTP Deploy Files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }} 
        server: ${{ secrets.SFTP_SERVER }} 
        local_path: './dist/*'
        remote_path: './'
        sftp_only: true
